# Generated by Django 5.2 on 2025-05-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_departamento_tipocontrato_empleado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tasa', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='rol',
            name='bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='iess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuotas', models.PositiveIntegerField(default=1)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoprestamo')),
            ],
        ),
    ]
