# Generated by Django 5.2 on 2025-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipoprestamo_alter_rol_bono_alter_rol_horas_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
